name: CI Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # This steps checkput the code from our repository
    - uses: actions/checkout@v2
   # This step sets up Node.js version 12.x on the runner
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
            node-version: 12.x
        # Here we run npm install in CI mode to have clean package installs
    - run: npm install
            # The demo I used is simple so we dont need to build it
        # that's why I jumped directly into running the tests
    - run: npm test
